### ISSUE TITLE
Hardware selection and other problems

### ISSUE THREAD

**Issue by jparta** [moracamilo/Bitcoin#2]
A major oversight is the random selection of hardware. You should have usage data for what mining equipment is actually used, otherwise this analysis seems quite flawed, even disregarding other obvious limitations such as using the current energy source makeup (where Chinese miners use quite a bit of hydro power, for example) and assuming fast and near-complete adoption.

**Comment by Camilo-Mora** [comment]
Our paper discussed this issue. And to handle it, we collected data on CO2 emissions for electricity generation in the countries where the mining is likely happening. Because data are not available about exactly where each mining ring is, we run a null model trying 1000 random combinations for each block being mined in any of those countries. Our expectation, and that agreed on by the reviewers, was that the real value would likely be in the range created.
